name: profile_editor
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  file_picker: ^10.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  fluttertoast: ^8.2.12
  get_it: ^8.0.3
  go_router: ^15.2.4 
  http: ^1.4.0
  mime: ^2.0.0
  path_provider: ^2.1.5
  cloudinary: ^1.2.0
  flutter_dotenv: ^5.2.1
  cached_network_image: ^3.4.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - .env
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400  
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500  
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600    
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
